[package]
org = "demo_epfl"
name = "poc_step1"
version = "0.1.0"
distribution = "2201.13.1"

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.7.2"
